2020-03-17 18:59:03,668 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-03-17 18:59:03,669 - INFO -my_log.py -API_AUTO -26-日志信息：.....此条用例需要校验数据库..... 
2020-03-17 18:59:03,703 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-03-17 18:59:03,715 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-03-17 18:59:03,716 - INFO -my_log.py -API_AUTO -26-日志信息：.....此条用例需要校验数据库..... 
2020-03-17 18:59:03,739 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-03-17 18:59:03,740 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-03-17 18:59:03,741 - INFO -my_log.py -API_AUTO -26-日志信息：.....此条用例需要校验数据库..... 
2020-03-17 18:59:03,760 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-03-17 18:59:03,762 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-03-17 18:59:03,763 - INFO -my_log.py -API_AUTO -26-日志信息：.....此条用例需要校验数据库..... 
2020-03-17 18:59:03,782 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-03-17 18:59:03,783 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-03-17 18:59:03,784 - INFO -my_log.py -API_AUTO -26-日志信息：.....此条用例需要校验数据库..... 
2020-03-17 18:59:03,802 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-03-30 16:40:16,168 - ERROR -my_log.py -API_AUTO -30-日志信息：111111 
NoneType: None
2020-04-01 17:02:21,106 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:02:21,248 - INFO -my_log.py -API_AUTO -26-日志信息：获取到的结果是：{'code': 200, 'success': True} 
2020-04-01 17:02:21,281 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-04-01 17:02:21,282 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:02:21,328 - INFO -my_log.py -API_AUTO -26-日志信息：获取到的结果是：{'code': 401, 'success': False, 'msg': '账号或密码错误'} 
2020-04-01 17:02:21,368 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-04-01 17:02:21,369 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:02:21,403 - INFO -my_log.py -API_AUTO -26-日志信息：获取到的结果是：{'code': 401, 'success': False, 'msg': '账号或密码错误'} 
2020-04-01 17:02:21,448 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-04-01 17:02:21,448 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:02:21,501 - INFO -my_log.py -API_AUTO -26-日志信息：获取到的结果是：{'code': 401, 'success': False, 'msg': '账号或密码错误'} 
2020-04-01 17:02:21,540 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-04-01 17:02:21,541 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:02:21,571 - INFO -my_log.py -API_AUTO -26-日志信息：获取到的结果是：{'code': 401, 'success': False, 'msg': '账号或密码错误'} 
2020-04-01 17:02:21,635 - INFO -my_log.py -API_AUTO -26-日志信息：----测试用例执行完成----- 
2020-04-01 17:08:58,457 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:08:58,574 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:08:58,634 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:08:58,671 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:08:58,718 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:13:39,830 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:13:39,938 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:13:39,985 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:13:40,037 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 17:13:40,090 - INFO -my_log.py -API_AUTO -26-日志信息：-----开始执行测试用例----- 
2020-04-01 19:02:40,731 - ERROR -my_log.py -API_AUTO -30-日志信息：111111 
NoneType: None
2020-04-01 19:11:55,253 - ERROR -my_log.py -API_AUTO -30-日志信息：111111 
NoneType: None
2020-04-01 19:11:55,253 - DEBUG -my_log.py -API_AUTO -24-日志信息：111111 
